version: '3.9'

services:
  db:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ok
      - MYSQL_DATABASE=rest_api_db2
      - MYSQL_USER=ok
      - MYSQL_PASSWORD=ok
      - MYSQL_PORT=3306
    env_file:
      - .env
    volumes:
      - ./prisma/migrations/20231114063528_sembah/:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    container_name: server
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://root:ok@host.docker.internal:3306/rest_api_db2?schema=public"
    volumes:
      - .:/app
